language: cpp
compiler:
    - gcc
notifications:
    email: false
env:
    - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install julia -y
    - git config --global user.name "Travis User"
    - git config --global user.email "travis@example.net"
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd());'
    - julia -e 'Pkg.add("DataFrames"); Pkg.add("DataArrays"); Pkg.add("BinDeps")'
    - julia -e 'Pkg.build("SQLite")'
    - julia test/test.jl
